# Generated by Django 2.2.2 on 2020-01-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_id', models.IntegerField(blank=True, null=True)),
                ('membership_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
