# Generated by Django 2.2.2 on 2020-01-31 04:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0003_auto_20200130_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterModelManagers(
            name='person',
            managers=[
                ('personman', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CaseAccessibleToUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manytomany.Case')),
            ],
        ),
    ]
