# Generated by Django 2.2.2 on 2020-01-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0004_auto_20200131_0451'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Case',
            new_name='Cases',
        ),
    ]
