# Generated by Django 2.2.2 on 2020-01-31 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0005_auto_20200131_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseaccessibletouser',
            name='case',
        ),
        migrations.AddField(
            model_name='caseaccessibletouser',
            name='case',
            field=models.ManyToManyField(to='manytomany.Cases'),
        ),
    ]
