# Generated by Django 2.2.2 on 2020-01-31 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manytomany', '0006_auto_20200131_0456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caseaccessibletouser',
            name='case',
        ),
        migrations.AddField(
            model_name='caseaccessibletouser',
            name='case',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='manytomany.Cases'),
            preserve_default=False,
        ),
    ]
